In [1]:
pip install pi-heaan

Note: you may need to restart the kernel to use updated packages.


In [2]:
import piheaan as heaan 
from piheaan.math import approx

# (STEP) parameter 설정 후 context 생성

In [58]:
params = heaan.ParameterPreset.FGb
context = heaan.make_context(params)
heaan.make_bootstrappable(context)

In [59]:
params

<ParameterPreset.FGb: 3>

In [60]:
context

# (STEP) context에 대한 secret key, public key 생성

In [61]:
key_dir_path='./key_new'
secret_key = heaan.SecretKey(context)
secret_key.save('./secret_key.bin')
key_generator = heaan.KeyGenerator(context, secret_key)
key_generator.gen_common_keys()
key_generator.save(key_dir_path)
public_key = key_generator.keypack

In [62]:
secret_key

In [64]:
public_key

# (STEP) message 메세지 슬롯 준비 

In [112]:
# byte 개수?
log_slots = heaan.get_log_full_slots(context)
log_slots

15

In [113]:
# 가능한 메세지 수?
num_slots = 2**log_slots
num_slots

32768

In [114]:
# 메세지에 들어갈 숫자데이터 준비
data = [i for i in range(num_slots)]
import numpy as np
np.array(data)

array([    0,     1,     2, ..., 32765, 32766, 32767])

In [76]:
message = heaan.Message(log_slots)
message

[ (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), ..., (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j) ]

# (STEP) message에 data 채워넣기

In [96]:
for i in range(num_slots):
    message[i] = data[i]

In [97]:
message

[ (0.000000+0.000000j), (1.000000+0.000000j), (2.000000+0.000000j), (3.000000+0.000000j), (4.000000+0.000000j), ..., (32763.000000+0.000000j), (32764.000000+0.000000j), (32765.000000+0.000000j), (32766.000000+0.000000j), (32767.000000+0.000000j) ]

# create encryptor 

In [100]:
encryptor = heaan.Encryptor(context)
encryptor

# create cipher text

In [119]:
ciphertext = heaan.Ciphertext(context)
ciphertext

(level: 24, log(num slots): 15, data: [ (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), ..., (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j) ])

In [105]:
type(ciphertext)

piheaan.Ciphertext

# 메세지 암호화 encrypt

In [116]:
encryptor.encrypt(message, public_key, ciphertext)

In [118]:
message

[ (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), ..., (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j) ]

In [117]:
ciphertext

(level: 12, log(num slots): 15, data: [ (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), ..., (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j) ])

# create decryptor

In [106]:
decryptor = heaan.Decryptor(context)
decryptor

# 평문을 복호화한 경우

In [107]:
plaintext = heaan.Plaintext(context)
plaintext

(level: 24, log(num slots): 15, data: [ (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), ..., (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j) ])

In [108]:
decryptor.decrypt(ciphertext, secret_key, plaintext)

In [109]:
plaintext

(level: 24, log(num slots): 15, data: [ (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), ..., (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j) ])

# 메세지를 복호화한 경우

In [110]:
decryptor.decrypt(ciphertext, secret_key, message)

In [111]:
message

[ (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), ..., (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j) ]

# 인코더+디코더 생성

In [120]:
endecoder = heaan.EnDecoder(context)
ptxt = endecoder.encode(message)
ptxt

(level: 12, log(num slots): 15, data: [ (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), ..., (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j) ])

In [121]:
message_decode = endecoder.decode(ptxt)
message_decode

[ (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), ..., (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j) ]

In [123]:
import numpy as np 
data1 = np.random.uniform(size = num_slots)
data1

array([0.2226138 , 0.02182574, 0.37117008, ..., 0.73932387, 0.92045283,
       0.54795305])

In [124]:
data2 = np.random.uniform(size=num_slots)
data2

array([0.56653801, 0.32737293, 0.29152684, ..., 0.20431785, 0.36486782,
       0.52899757])

In [129]:
len(data2)

32768

In [126]:
message1 = heaan.Message(log_slots)
message1

[ (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), ..., (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j) ]

In [127]:
log_slots

15

In [128]:
num_slots

32768

In [130]:
message2 = heaan.Message(log_slots)
message2

[ (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), ..., (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j) ]

In [131]:
for i in range(num_slots):
    message1[i] = data1[i]
    message2[i] = data2[i]

In [132]:
message1

[ (0.222614+0.000000j), (0.021826+0.000000j), (0.371170+0.000000j), (0.884654+0.000000j), (0.452554+0.000000j), ..., (0.258198+0.000000j), (0.216032+0.000000j), (0.739324+0.000000j), (0.920453+0.000000j), (0.547953+0.000000j) ]

In [133]:
message2

[ (0.566538+0.000000j), (0.327373+0.000000j), (0.291527+0.000000j), (0.040160+0.000000j), (0.269352+0.000000j), ..., (0.678111+0.000000j), (0.482374+0.000000j), (0.204318+0.000000j), (0.364868+0.000000j), (0.528998+0.000000j) ]

In [134]:
encryptor = heaan.Encryptor(context)
ciphertext1 = heaan.Ciphertext(context)
ciphertext1

(level: 24, log(num slots): 15, data: [ (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), ..., (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j) ])

In [135]:
ciphertext2 = heaan.Ciphertext(context)
ciphertext2

(level: 24, log(num slots): 15, data: [ (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), ..., (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j), (0.000000+0.000000j) ])

In [136]:
ciphertext1 == ciphertext2

False

In [138]:
encryptor.encrypt(message1, public_key, ciphertext1)
encryptor.encrypt(message2, public_key, ciphertext2)

In [139]:
help(heaan.HomEvaluator)

Help on class HomEvaluator in module piheaan:

class HomEvaluator(pybind11_builtins.pybind11_object)
 |  Method resolution order:
 |      HomEvaluator
 |      pybind11_builtins.pybind11_object
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(...)
 |      __init__(*args, **kwargs)
 |      Overloaded function.
 |      
 |      1. __init__(self: piheaan.HomEvaluator, context: piheaan.Context, key_dir_path: str) -> None
 |      
 |      construct a homevaluator from context and key_dir_path
 |      
 |      2. __init__(self: piheaan.HomEvaluator, context: piheaan.Context, pack: piheaan.KeyPack) -> None
 |      
 |      construct a homevaluator from context and keypack
 |  
 |  add(...)
 |      add(*args, **kwargs)
 |      Overloaded function.
 |      
 |      1. add(self: piheaan.HomEvaluator, op1: piheaan.Message, cnst: complex, res: piheaan.Message) -> None
 |      
 |      2. add(self: piheaan.HomEvaluator, op1: piheaan.Message, op2: piheaan.Message, res: piheaan

In [140]:
help(heaan.Ciphertext)

Help on class Ciphertext in module piheaan:

class Ciphertext(pybind11_builtins.pybind11_object)
 |  Method resolution order:
 |      Ciphertext
 |      pybind11_builtins.pybind11_object
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(...)
 |      __init__(*args, **kwargs)
 |      Overloaded function.
 |      
 |      1. __init__(self: piheaan.Ciphertext, context: piheaan.Context) -> None
 |      
 |      construct a dummy ciphertext
 |      
 |      2. __init__(self: piheaan.Ciphertext, context: piheaan.Context, log_slots: int) -> None
 |      
 |      construct a dummy ciphertext based on given log_slots
 |      
 |      3. __init__(self: piheaan.Ciphertext, ctxt: piheaan.Ciphertext) -> None
 |      
 |      copying
 |  
 |  __len__(...)
 |      __len__(self: piheaan.Ciphertext) -> int
 |  
 |  __repr__(...)
 |      __repr__(self: piheaan.Ciphertext) -> str
 |  
 |  load(...)
 |      load(self: piheaan.Ciphertext, file_path: str) -> None
 |  
 |  save(...)
 |

In [141]:
evaluator = heaan.HomEvaluator(context, public_key)
evaluator

In [143]:
ciphertext_out_add = heaan.Ciphertext(context)
ciphertext_out_sub = heaan.Ciphertext(context)
ciphertext_out_mult = heaan.Ciphertext(context)

In [144]:
evaluator.add(ciphertext1, ciphertext2, ciphertext_out_add)
evaluator.sub(ciphertext1, ciphertext2, ciphertext_out_sub)
evaluator.mult(ciphertext1, ciphertext2, ciphertext_out_mult)

In [145]:
ciphertext_out_scalar_add = heaan.Ciphertext(context)
ciphertext_out_scalar_mult = heaan.Ciphertext(context)

In [147]:
a_scalar = 1/13
evaluator.add(ciphertext1, a_scalar, ciphertext_out_scalar_add)

In [148]:
m_scalar = 1/17
evaluator.mult(ciphertext1, m_scalar, ciphertext_out_scalar_mult)

In [149]:
decryptor = heaan.Decryptor(context)